const test = {
    '3d-porn': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    aesthetic: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    amateur: [ 'gif', 'mp4', 'png', 'jpg' ],
    anal: [ 'gif', 'mp4', 'jpg', 'jpeg' ],
    asian: [ 'mp4', 'png', 'jpg' ],
    asmr: [ 'mp4' ],
    ass: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'bath-shower': [ 'gif', 'mp4', 'png', 'jpg' ],
    bdsm: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    boobs: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    cock: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    cosplay: [ 'mp4', 'png', 'jpg' ],
    creampie: [ 'gif', 'mp4', 'jpg', 'jpeg' ],
    cuckhold: [ 'gif', 'mp4', 'jpg' ],
    cumshots: [ 'gif', 'mp4', 'jpg' ],
    dilf: [ 'gif', 'mp4', 'png', 'jpg' ],
    'double-penetration': [ 'gif', 'jpg' ],
    ebony: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    feet: [ 'gif', 'png', 'jpg', 'jpeg' ],
    femdom: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    fisting: [ 'gif', 'jpg' ],
    'food-play': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    funny: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    furry: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'glory-hole': [ 'gif', 'mp4' ],
    goth: [ 'mp4', 'png', 'jpg' ],
    hands: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'hentai-no-loli': [ 'gif', 'png', 'jpg', 'jpeg' ],
    hentai: [ 'gif' ],
    horror: [ 'mp4', 'png', 'jpg', 'jpeg' ],
    interracial: [ 'gif', 'mp4', 'jpg' ],
    joi: [ 'gif', 'mp4' ],
    lactation: [ 'gif', 'mp4', 'png', 'jpeg' ],
    latin: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'lgbt-bisexual': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'lgbt-femboy': [ 'mp4', 'png', 'jpg', 'jpeg' ],
    'lgbt-gay': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'lgbt-lesbian': [ 'gif', 'mp4', 'png', 'jpg' ],
    'lgbt-transgender': [ 'mp4', 'png', 'jpg' ],
    'lgbt-twink': [ 'mp4', 'png', 'jpg' ],
    lingerie: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    massage: [ 'gif', 'mp4', 'jpg', 'jpeg' ],
    mature: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    milf: [ 'gif', 'mp4', 'jpg', 'jpeg' ],
    'naked-wrestling': [ 'gif', 'mp4', 'jpg' ],
    oral: [ 'gif', 'mp4', 'png', 'jpg' ],
    orgy: [ 'gif', 'mp4', 'jpg' ],
    pegging: [ 'gif', 'mp4', 'jpg' ],
    petite: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    'plus-size': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    pornstar: [ 'gif', 'mp4', 'jpg' ],
    pov: [ 'gif', 'mp4', 'png', 'jpg' ],
    public: [ 'gif', 'mp4', 'png', 'jpg' ],
    pussy: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    rimming: [ 'gif', 'mp4' ],
    rough: [ 'gif', 'mp4', 'png', 'jpg' ],
    solo: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    squirting: [ 'gif', 'mp4', 'jpg' ],
    'tattoos-piercings': [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    tease: [ 'gif', 'mp4', 'jpg' ],
    thighs: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    threesomes: [ 'gif', 'mp4', 'png', 'jpg' ],
    toys: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    uniform: [ 'gif', 'mp4', 'jpg' ],
    vintage: [ 'gif', 'mp4', 'png', 'jpg', 'jpeg' ],
    watersports: [ 'gif', 'mp4', 'png', 'jpg' ]
  }